name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest allure-pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests with pytest
      run: |
        pytest api_test.py --alluredir=allure-results

    - name: Generate Allure report
      run: |
        allure generate allure-results -o allure-report --clean

    - name: Upload Allure report as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report
